# Generated by Django 5.1.1 on 2024-11-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place_de_fete',
            name='designation',
            field=models.CharField(choices=[('vip', 'VIP'), ('salle_conference', 'Salle de conference'), ('hall0', "Hall à l'entré"), ('hall1', 'Hall au premier étage')], max_length=100, unique=True),
        ),
    ]
