# Generated by Django 5.1.1 on 2024-11-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_place_de_fete_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_evenement',
            name='nombre_invites',
            field=models.IntegerField(choices=[('petit', '01 à 10'), ('cinquantaine', '11 à 50'), ('centaine', '51 à 100'), ('cent_cinquantaine', '101 à 150'), ('deux_centaine', '151 à 200'), ('trois_centaine', '200 à 300'), ('maximum', 'Plus de 300')], verbose_name="Nombres d'invités approximatif"),
        ),
    ]
