# Generated by Django 5.1.1 on 2024-11-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reservation_evenement_nombre_invites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambres',
            name='type',
            field=models.CharField(choices=[('ventile', 'Chambre ventilée'), ('climatise', 'Chambre climatisée'), ('suite', 'Suite')], max_length=50, verbose_name='Type de chambre'),
        ),
    ]
