# Generated by Django 5.1.1 on 2025-01-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_reservation_evenement_nombre_invites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status_reservation',
            field=models.CharField(choices=[('en_cours', 'En cours...'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='en_cours', max_length=15, verbose_name='Status de la réservation'),
        ),
    ]
