# Generated by Django 5.1.1 on 2025-01-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_reservation_status_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambres',
            name='prix_heure',
            field=models.IntegerField(verbose_name='Prix par heure'),
        ),
        migrations.AlterField(
            model_name='chambres',
            name='prix_nuitee',
            field=models.IntegerField(verbose_name='Prix par nuitée'),
        ),
        migrations.AlterField(
            model_name='place_de_fete',
            name='prix',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation_chambre',
            name='cout',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation_evenement',
            name='cout',
            field=models.IntegerField(),
        ),
    ]
